### ISSUE TITLE
Consume too much memory

### ISSUE THREAD

**Issue by wangdsh** [TheAtticusProject/cuad#6]
When "Creating features from dataset file at .", this code consumes too much memory (I have a 48G machine).

This makes me can not run this code. (I guess this needs a 128G machine)

Is it possible to fix this problem? Thx.

**Comment by TheAtticusProject** [comment]
Unfortunately there is no simple way to reduce the memory consumption, as this is due to the underlying huggingface code that we adapted, but we found that this was not a problem on our machines. However, note that the features are saved after being created so the feature creation code only has to run once.

**Comment by IsCoelacanth** [comment]
doesn't fit in 256GB RAM either, using big-bird tokenizer with 2048 seq length and 512 strides, goes out of memory after 60% of the dataset.
